name: Check schema flow

on:
  workflow_call:
    inputs:
      azure-dir:
        description: 'Directory containing Azure Pipelines config files. Provide an empty string to skip checking on Azure Pipelines files.'
        default: './.azure/'
        required: false
        type: string

jobs:
  schema:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install check-jsonschema

      - name: Scan repo
        run: python -c "import os; is_dir = os.path.isdir('.github/actions'); print(f'GH_ACTIONS={int(is_dir)}')" >> $GITHUB_ENV

      # https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/github-workflow.json
      - name: GitHub Actions - workflow
        run: check-jsonschema -v $(find .github/workflows -name '*.yml' -a ! -name '_*.yml') --builtin-schema "github-workflows"

      # https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/github-action.json
      - name: GitHub Actions - action
        if: ${{ env.GH_ACTIONS == '1' }}
        run: check-jsonschema -v .github/actions/*/*.yml --builtin-schema "github-actions"

      # https://github.com/microsoft/azure-pipelines-vscode/blob/main/service-schema.json
      - name: Azure Pipelines
        if: ${{ inputs.azure-dir != '' }}
        env:
          SCHEMA_FILE: https://raw.githubusercontent.com/microsoft/azure-pipelines-vscode/v1.205.0/service-schema.json
        run: |
          check-jsonschema -v ${{ inputs.azure-dir }}/*.yml --schemafile "$SCHEMA_FILE"
