name: Check Markdown links
# https://github.com/gaurav-nelson/github-action-markdown-link-check

on:
  workflow_call:
    inputs:
      config-file:
        description: 'Config file (JSON) used for markdown link checks'
        required: true
        type: string  
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened, ready_for_review, synchronize]
    paths:
      - ".github/workflows/md-check-links.yml"
      - "**/*.md"

jobs:
  markdown-link-check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        config-file: ${{ inputs.config-file }}
