name: Check package flow

on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'Unique name for collecting artifacts'
        required: true
        type: string
      import-name:
        description: 'Import name to test with after installation'
        required: true
        type: string
      install-flags:
        description: 'Additional pip install flags'
        required: false
        type: string
        default: ""
      build-matrix:
        description: 'what building configs in json format'
        required: false
        type: string
        default: |
          {
            "os": ["ubuntu-latest"],
          }
      testing-matrix:
        description: 'what test configs to run in json format'
        required: false
        type: string
        # default operating systems should be pinned to specific versions instead of "-latest" for stability
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
        default: |
          {
            "os": ["ubuntu-20.04", "macos-11", "windows-2022"],
            "python-version": ["3.7", "3.9"]
          }

defaults:
  run:
    shell: bash

jobs:

  init-store:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3
    - run: mkdir dist && touch dist/.placeholder
    - name: Upload 📤
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
        path: dist

  pkg-build:
    needs: init-store
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1  # run sequential to prevent download/upload collisions
      fail-fast: false
      matrix: ${{ fromJSON(inputs.build-matrix) }}

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3
    - name: Set up Python 🐍
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    # TODO: this breaks external use
    - name: Create package 📦
      uses: ./.github/actions/pkg-create
      with:
        artifact-name: ${{ inputs.artifact-name }}

  pkg-check:
    needs: pkg-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(inputs.testing-matrix) }}

    steps:
    - name: Set up Python 🐍 ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # TODO: this breaks external use
    - name: Installing package 📦
      uses: ./.github/actions/pkg-install
      with:
        artifact-name: ${{ inputs.artifact-name }}
        import-name: ${{ inputs.import-name }}
        pip-flags: ${{ inputs.install-flags }}

    # TODO: add run doctests
