name: Check docs flow

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        default: '3.9'
        required: false
        type: string
      docs-dir:
        description: 'Working directory to run make docs in'
        default: './docs'
        required: false
        type: string
      timeout-minutes:
        description: 'timeout-minutes for each job'
        default: 15
        required: false
        type: number
      pip-install-extra:
        description: 'A full pip command to install extra dependencies for doctest.'
        default: 'pip install -e ".[dev]" -U --extra-index-url https://download.pytorch.org/whl/cpu'
        required: false
        type: string

jobs:

  doctest:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          pip install -e ".[docs]" -U --extra-index-url https://download.pytorch.org/whl/cpu
          if [ -n "${{ inputs.pip-install-extra }}" ]; then
            ${{ inputs.pip-install-extra }}
          fi
          python --version
          pip --version
          pip list
        shell: bash

      - name: Test Documentation
        working-directory: ${{ inputs.docs-dir }}
        env:
          SPHINX_MOCK_REQUIREMENTS: 0
        run: |
          make doctest
          make coverage

  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          pip install -e ".[docs]" -U --extra-index-url https://download.pytorch.org/whl/cpu
          sudo apt-get update --fix-missing
          sudo apt-get install -y texlive-latex-extra dvipng texlive-pictures
          python --version
          pip --version
          pip list

      - name: Build documentation
        working-directory: ${{ inputs.docs-dir }}
        run: make html --debug SPHINXOPTS="-W --keep-going"

      - name: Upload built docs
        uses: actions/upload-artifact@v3
        with:
          name: docs-${{ github.sha }}
          path: ${{ inputs.docs-dir }}/build/html/
        if: success()
