name: Check package flow

on:
  workflow_call:
    inputs:
      actions-ref:
        description: "Version of actions, normally the same as workflow"
        required: true
        type: string
      artifact-name:
        description: "Unique name for collecting artifacts"
        required: true
        type: string
      install-extras:
        description: "optional extras which are needed to include also []"
        required: false
        type: string
        default: ""
      install-flags:
        description: "Additional pip install flags"
        required: false
        type: string
        default: "-f https://download.pytorch.org/whl/cpu/torch_stable.html"
      import-name:
        description: "Import name to test with after installation"
        required: true
        type: string
      custom-import:
        description: "additional import statement, need to be full python code"
        type: string
        required: false
        default: ""
      build-matrix:
        description: "what building configs in json format, expected keys are `os` and `python-version`"
        required: false
        type: string
        default: |
          {
            "os": ["ubuntu-latest"],
          }
      testing-matrix:
        description: "what test configs to run in json format, expected keys are `os` and `python-version`"
        required: false
        type: string
        # default operating systems should be pinned to specific versions instead of "-latest" for stability
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
        default: |
          {
            "os": ["ubuntu-20.04", "macos-11", "windows-2022"],
            "python-version": ["3.8", "3.9"]
          }

defaults:
  run:
    shell: bash

jobs:
  init-store: #  todo: remove this wne download will be fault tolerant
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: mkdir dist && touch dist/.placeholder
      - name: Upload 📤
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: dist
          include-hidden-files: true

  pkg-build:
    needs: init-store
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1 # run sequential to prevent download/upload collisions
      fail-fast: false
      matrix: ${{ fromJSON(inputs.build-matrix) }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version || '3.x' }}

      - name: Pull reusable 🤖 actions️
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.actions-ref }}
          path: .cicd
          repository: Lightning-AI/utilities
      - name: Prepare build env.
        run: pip install -r ./.cicd/requirements/gha-package.txt
      - name: Create package 📦
        uses: ./.cicd/.github/actions/pkg-create
        with:
          artifact-name: ${{ inputs.artifact-name }}

  pkg-check:
    needs: pkg-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(inputs.testing-matrix) }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python 🐍 ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version || '3.x' }}

      - name: Pull reusable 🤖 actions️
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.actions-ref }}
          path: .cicd
          repository: Lightning-AI/utilities
      - name: Installing package 📦
        timeout-minutes: 20
        uses: ./.cicd/.github/actions/pkg-install
        with:
          artifact-name: ${{ inputs.artifact-name }}
          pkg-extras: ${{ inputs.install-extras }}
          pip-flags: ${{ inputs.install-flags }}
          import-name: ${{ inputs.import-name }}
          custom-import: ${{ inputs.custom-import }}

    # TODO: add run doctests

  pkg-guardian:
    runs-on: ubuntu-latest
    needs: pkg-check
    if: always()
    steps:
      - run: echo "${{ needs.pkg-check.result }}"
      - name: failing...
        if: needs.pkg-check.result == 'failure'
        run: exit 1
      - name: cancelled or skipped...
        if: contains(fromJSON('["cancelled", "skipped"]'), needs.pkg-check.result)
        timeout-minutes: 1
        run: sleep 90
