name: Check Markdown links
# https://github.com/gaurav-nelson/github-action-markdown-link-check

on:
  workflow_call:
    inputs:
      config-file:
        description: 'Config file (JSON) used for markdown link checks'
        required: true
        type: string

jobs:
  markdown-link-check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        config-file: ${{ inputs.config-file }}
