name: Test scripts

on:
  push:
    branches: [main, "release/*"]
  pull_request:
    branches: [main, "release/*"]

defaults:
  run:
    shell: bash

jobs:
  test-scripts:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04", "macos-13", "windows-2022"]
        python-version: ["3.8", "3.12"]
    timeout-minutes: 35
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python 🐍 ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        timeout-minutes: 5
        run: |
          pip install -r requirements/_tests.txt
          pip --version
          pip list

      - name: test Scripts
        working-directory: ./scripts
        run: pytest . -v

  scripts-guardian:
    runs-on: ubuntu-latest
    needs: test-scripts
    if: always()
    steps:
      - run: echo "${{ needs.test-scripts.result }}"
      - name: failing...
        if: needs.test-scripts.result == 'failure'
        run: exit 1
      - name: cancelled or skipped...
        if: contains(fromJSON('["cancelled", "skipped"]'), needs.test-scripts.result)
        timeout-minutes: 1
        run: sleep 90
