name: Apply checks

on:
  push:
    branches: [main, "release/*"]
  pull_request:
    branches: [main, "release/*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')) }}

jobs:
  check-code:
    uses: ./.github/workflows/check-code.yml
    with:
      actions-ref: ${{ github.sha }} # use local version
      extra-typing: "typing"

  check-schema-latest:
    uses: ./.github/workflows/check-schema.yml
    with:
      azure-dir: ""

  check-schema-fixed:
    uses: ./.github/workflows/check-schema.yml
    with:
      actions-ref: ${{ github.sha }} # use local version
      azure-dir: ""

  check-schema:
    runs-on: ubuntu-latest
    # just aggregation of the previous two jobs
    needs: ["check-schema-latest", "check-schema-fixed"]
    steps:
      - run: echo "done"

  check-package:
    uses: ./.github/workflows/check-package.yml
    with:
      actions-ref: ${{ github.sha }} # use local version
      artifact-name: dist-packages-${{ github.sha }}
      import-name: "lightning_utilities"
      testing-matrix: |
        {
          "os": ["ubuntu-22.04", "macos-12", "windows-2022"],
          "python-version": ["3.7", "3.12"]
        }

  check-docs:
    uses: ./.github/workflows/check-docs.yml
    with:
      requirements-file: "requirements/dev-docs.txt"
      install-tex: true

  check-md-links:
    uses: ./.github/workflows/check-md-links.yml
    #with:
    #  config-file: ".github/markdown.links.config.json"
