name: Apply checks

on:
  push:
    branches: [main, "release/*"]
  pull_request:
    branches: [main, "release/*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')) }}

jobs:
  check-typing:
    uses: ./.github/workflows/check-code.yml

  check-schema:
    uses: ./.github/workflows/check-schema.yml
    with:
      azure-dir: ""

  check-package:
    uses: ./.github/workflows/check-package.yml
    with:
      import-name: "pl_devtools"
      pypi-name: "lightning-devtools"

  check-docs:
    uses: ./.github/workflows/check-docs.yml
