name: Cleaning caches

on:
  workflow_call:
    inputs:
      pattern:
        description: 'string to grep cache keys with'
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  cleanup-caches:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GRID_AI_GITHUB_TOKEN }}
      - name: install requirements
        run: pip install -U fire requests pandas
      - name: List and Filer caches
        run: |
          python .github/scripts/find-unused-caches.py \
            --repository="${{ github.repository }}" --token=${{ secrets.GRID_AI_GITHUB_TOKEN }} --dalay_days=2
          cat unused-cashes.txt
      - name: Delete caches
        if: github.event_name != 'pull_request'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Use a while loop to read each line from the file
          while read -r line || [ -n "$line" ]; do
              echo "$line";
              # delete each cache based on file...
              gh api --method DELETE  -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/actions/caches/ $line;
          done < "unused-cashes.txt"
