name: Clear cache flow

on:
  workflow_call:
    inputs:
      pattern:
        description: 'string to grep cache keys with'
        required: true
        type: string

jobs:
  clear-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Get the list of cache keys
        run: |
          gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/actions/caches --paginate --jq ".actions_caches[].key" | sort | uniq > cache_keys.txt
          cat cache_keys.txt

      - name: Filter cache keys
        run: |
          grep -E ${{ inputs.pattern }} cache_keys.txt > cache_keys_to_remove.txt
          cat cache_keys_to_remove.txt

      - name: Remove caches
        run: |
          for key in $(cat cache_keys_to_remove.txt); do
            gh api --method DELETE -H "Accept: application/vnd.github+json" "/repos/${{ github.repository }}/actions/caches?key=${key}"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show the list of remaining caches
        run: |
          gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/actions/caches
