name: Check Code formatting

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request, but only for the master branch
  push: {}
  pull_request:
    branches: [master]

jobs:

  typing-check-mypy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install mypy
        run: |
          pip install mypy
          pip list
      - name: mypy
        run: |
          mypy
