name: Clear cache weekly

on:
  schedule:
    # on Sunday's night 2am
    - cron: "0 2 * * 7"
  pull_request:
    paths:
      - ".github/scripts/find-unused-caches.py"
      - ".github/workflows/cleanup-caches.yml"
      - ".github/workflows/cron-clear-cache.yml"

  workflow_dispatch:
    inputs:
      pattern:
        description: 'patter for cleaning cache'
        default: "pip"
        required: false
        type: string

jobs:

  drop-unused-caches:
    uses: ./.github/workflows/cleanup-caches.yml
    with:
      # ise input if set of default...
      pattern: ${{ inputs.pattern || 'pip|conda' }}
