# This is just an example of how to use reusable workflows
name: pull

on:
  push:
    branches: [master, "release/*"]
  pull_request:
    branches: [master, "release/*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')) }}

jobs:
  check-typing:
    uses: ./.github/workflows/check-typing.yml

  check-typing:
    uses: ./.github/workflows/check-schema.yml
